### ISSUE TITLE
it seems to conflict with injectionforxcode

### ISSUE THREAD

**Issue by faimin** [Forkong/FKRealGroup#1]
it seems to conflick with [injectionforxcode](https://github.com/johnno1962/injectionforxcode), because after i install it and load Bundle,there is a waring" it could not bind service socket:address already in use".
then i uninstall injectionforxcode, it's ok

**Comment by Forkong** [comment]
In InjectionLoader, I found this code.
`
else if ( bind( serverSocket, (struct sockaddr *)&serverAddr, sizeof serverAddr ) < 0 )
        [self error:@"Could not bind service socket: %s. "
         "Kill any \"ibtoold\" processes and restart.", strerror( errno )];
`
This is a socket bind problem, but I didn't use socket.

It is interesting to note that if you manually move FKRealGroup.xcplugin to `~/Library/Application Support/Developer/Shared/Xcode/Plug-ins`, that there would be no problem.

If your Xcode contains InjectionLoader, and you run(Command+R) FKRealGroup project directly, InjectionLoader will alert “Could not bind service socket…”.

So, if you just build(Command+B) FKRealGroup,then restart. It seems no problem.

FKRealGroup will support Alcatraz soon. Use Alcatraz will be no problem.

**Comment by faimin** [comment]
YES, I run the FKRealGroup project manually,because my Alcatraz can't search the FKRealGroup, perhaps my version is old or this plugin has't sync to server.

Whatever,thank you for your answer,this plugin is convenient than synx

**Comment by Forkong** [comment]
Thanks, happy to help!
