### ISSUE TITLE
为啥 会和 AMAppExportToIPA  这个插件发生冲突了

### ISSUE THREAD

**Issue by gaoxiao228** [Forkong/FKRealGroup#3]
装了AMAppExportToIPA 这个插件, 用了FKRealGroup插件新建完文件夹,再右击文件夹, Xcode 就会闪退...  提示  "Xcode quit unexpectedly while using the AMAppExportToIPA plug-in."
![83f246c6-8f5f-4f91-9c14-14e4db417034](https://cloud.githubusercontent.com/assets/1780502/13275506/e9ad9e1c-daf0-11e5-9fc4-96e269e0a3a8.png)

**Comment by Forkong** [comment]
好的，我去检查一下。
感谢你的反馈。

**Comment by Forkong** [comment]
在`AMAppExportToIPA`的`NSObject+PopupMenu.m`中，有这么一个方法：

```
- (void)AM_popUpContextMenu:(NSMenu *)arg1 withEvent:(NSEvent *)arg2 forView:(NSView *)arg3 withFont:(id)arg4
```

此方法会在导航区右击单个、多个文件或文件夹的时候，移除所有右击Menu的item，所以`FKRealGroup`在往右击菜单中插入值的时候会插入错误，我可以修改一下避免这个崩溃。

但是由于`FKRealGroup`和`AMAppExportToIPA`都需要在右键菜单中插入选项，而我们实现方式又不一样，所以即使我直接修改过来，依然会出现右击没有任何选项的问题。

我建议你给`AMAppExportToIPA`的作者提交一个Issue, 让他去除`NSObject+PopupMenu.m`中的第55行：`[arg1 removeAllItems];`,而改用其他方式，他的修改应该量应该会小一些。
