### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by zy30651** [Forkong/FKRealGroup#4]
原因是 我新建了文件夹，目录下已经有这个名字了，就命名后重名，让我修改，我修改再保存就报错，报错说没权限。我本想算了删除名字回车，系统原来会恢复默认创建的名字，他不行只能手输入新建文件夹，然后重新命名有报错。然后就崩溃了。本想看看你哪出的问题。发现代码还封装起来了。我已经无语了。

**Comment by Forkong** [comment]
感谢你的反馈，我会尽快处理这个问题。
能把你的报错信息一起附上来吗？

**Comment by Forkong** [comment]
我尝试了一下，没有权限应该是没有正确获取到文件夹路径，在创建文件夹的时候，就在根目录下创建了，例如，新文件夹名称为`test`，结果创建位置为`/test`，所有说没有权限。我修改为，如果没有正确获取路径，允许完成，但不创建真实文件夹，并给予警告。
崩溃问题我并不清除，需要你附上崩溃报告。
建议你通过Alcatraz卸载重装一下，谢谢！
