### ISSUE TITLE
xcode7.2 没有 工具栏中没有plugin，FKRealGroup无法使用

### ISSUE THREAD

**Issue by BigFengFeng** [Forkong/FKRealGroup#7]
![2016-09-30 12 01 25](https://cloud.githubusercontent.com/assets/17843083/18980315/a5cbe192-8705-11e6-870f-4c5fb85b1078.png)

**Comment by Forkong** [comment]
1. 在`~/Library/Application Support/Developer/Shared/Xcode/Plug-ins`目录下看看有没有这个插件。
2. 安装完成后是否重启Xcode，重启之后，是否load bundle。
3. 使用Alcatraz安装，之后再重启Xcode。
